import { useState } from "react";
import { useEskulStore } from "@/stores/eskulStore";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter, DialogClose } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PlusCircle, BookOpen } from "lucide-react";

const MateriMingguan = () => {
  const { kelasAktif, materi, tambahMateri } = useEskulStore((state) => ({
    kelasAktif: state.kelasAktif,
    materi: state.materi,
    tambahMateri: state.tambahMateri,
  }));

  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [minggu, setMinggu] = useState(1);
  const [judul, setJudul] = useState("");
  const [deskripsi, setDeskripsi] = useState("");
  const [linkVideo, setLinkVideo] = useState("");

  if (!kelasAktif) {
    return null;
  }

  const materiDiKelas = materi[kelasAktif] || [];

  const handleAddMateri = () => {
    if (!judul || !deskripsi || !kelasAktif) {
      alert("Judul dan Deskripsi harus diisi.");
      return;
    }

    tambahMateri({
      id: "", // generated by store
      kelasId: kelasAktif,
      minggu,
      judul,
      deskripsi,
      linkVideo,
    });

    // Reset form and close dialog
    setJudul("");
    setDeskripsi("");
    setLinkVideo("");
    setIsDialogOpen(false);
  };

  return (
    <Card>
      <CardHeader className="flex flex-row items-center justify-between">
        <div>
          <CardTitle>Materi Mingguan</CardTitle>
          <CardDescription>Kelola materi pembelajaran per minggu.</CardDescription>
        </div>
        <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
          <DialogTrigger asChild>
            <Button variant="outline" size="sm">
              <PlusCircle className="h-4 w-4 mr-2" />
              Tambah Materi
            </Button>
          </DialogTrigger>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Tambah Materi Baru</DialogTitle>
            </DialogHeader>
            <div className="grid gap-4 py-4">
              <Input type="number" placeholder="Minggu ke-" value={minggu} onChange={e => setMinggu(parseInt(e.target.value, 10))} />
              <Input placeholder="Judul Materi" value={judul} onChange={e => setJudul(e.target.value)} />
              <Textarea placeholder="Deskripsi singkat" value={deskripsi} onChange={e => setDeskripsi(e.target.value)} />
              <Input placeholder="Link Video (opsional)" value={linkVideo} onChange={e => setLinkVideo(e.target.value)} />
            </div>
            <DialogFooter>
              <DialogClose asChild><Button type="button" variant="secondary">Batal</Button></DialogClose>
              <Button type="submit" onClick={handleAddMateri}>Simpan</Button>
            </DialogFooter>
          </DialogContent>
        </Dialog>
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {materiDiKelas.length > 0 ? (
            materiDiKelas.map(m => (
              <div key={m.id} className="p-4 border rounded-lg">
                <h4 className="font-semibold">Minggu {m.minggu}: {m.judul}</h4>
                <p className="text-sm text-muted-foreground">{m.deskripsi}</p>
                {m.linkVideo && <a href={m.linkVideo} target="_blank" rel="noopener noreferrer" className="text-sm text-blue-500 hover:underline">Tonton Video</a>}
              </div>
            ))
          ) : (
            <div className="text-center text-muted-foreground py-8">
              <BookOpen className="mx-auto h-12 w-12" />
              <p className="mt-4">Belum ada materi untuk kelas ini.</p>
            </div>
          )}
        </div>
      </CardContent>
    </Card>
  );
};

export default MateriMingguan;
